version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/travis-demo
hooks:
  AfterInstall: 
    - location: after_install.sh
  ApplicationStart: 
    - location: application_start.sh